package com.yg.service.dao.menu;

import com.yg.service.bean.menu.YgMenu;
import org.apache.ibatis.annotations.Param;
import java.util.List;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface YgMenuDao {

	public YgMenu findYdMenuById(Integer id);

	public Integer insert(YgMenu param);

	public Integer getYdMenuCount(YgMenu param);

	public List<YgMenu> getAllListByGroupCode(@Param("groupCode") String groupCode);

	public List<YgMenu> findYdMenusByPage(@Param("param") YgMenu param, @Param("offset") Integer offset, @Param("rows") Integer rows);
	
	//if not use,pls delete it
	public Integer deleteYdMenuById(Integer id);
}