package com.yd.service.dao.permission;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yd.service.bean.permission.YdPermission;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface YdPermissionDao {

	public YdPermission findYdPermissionById(Integer id);
	
	public Integer insert(YdPermission param);
	
	public Integer getYdPermissionCount(YdPermission param);
	
	public List<YdPermission> findYdPermissionsByPage(@Param("param")YdPermission param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteYdPermissionById(Integer id);

	public YdPermission findPermissionByAliasAndPid(@Param("alias")String alias, @Param("pid")int pid);

	public YdPermission findPermissionByAlias(@Param("alias")String alias);

	public void updateById(@Param("param")YdPermission item);

	public List<YdPermission> findYdPermissionByGroupCode(@Param("groupCode")String groupCode);
}