package com.yd.service.dao.permission;

import java.util.List;
import java.lang.Integer;
import org.apache.ibatis.annotations.Param;
import com.yd.service.bean.permission.YdRole;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface YdRoleDao {

	public YdRole findYdRoleById(Integer id);
	
	public Integer insert(YdRole param);
	
	public Integer getYdRoleCount(YdRole param);
	
	public List<YdRole> findYdRolesByPage(@Param("param")YdRole param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteYdRoleById(Integer id);

	public void updateRoleName(@Param("roleId")Integer roleId, @Param("roleName")String roleName);

	public List<String> getPermissionListByRoles(@Param("roleIdList")List<Integer> roleIdList);
}