package com.yd.service.dao.menu;

import java.util.List;
import java.lang.Integer;
import org.apache.ibatis.annotations.Param;
import com.yd.service.bean.menu.YdMenu;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface YdMenuDao {

	public YdMenu findYdMenuById(Integer id);
	
	public Integer insert(YdMenu param);
	
	public Integer getYdMenuCount(YdMenu param);
	
	public List<YdMenu> getAllListByGroupCode(@Param("groupCode")String groupCode);
	
	public List<YdMenu> findYdMenusByPage(@Param("param")YdMenu param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteYdMenuById(Integer id);
}