package com.yg.service.dao.permission;

import com.yg.service.bean.permission.YgRole;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface YgRoleDao {

	public YgRole findYdRoleById(Integer id);

	public Integer insert(YgRole param);

	public Integer getYdRoleCount(YgRole param);

	public List<YgRole> findYdRolesByPage(@Param("param") YgRole param, @Param("offset") Integer offset, @Param("rows") Integer rows);

	//if not use,pls delete it
	public Integer deleteYdRoleById(Integer id);

	public void updateRoleName(@Param("roleId") Integer roleId, @Param("roleName") String roleName);

	public List<String> getPermissionListByRoles(@Param("roleIdList") List<Integer> roleIdList);
}