package com.yd.service.crawer.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yd.service.crawer.bean.CrawerBrand;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface CrawerBrandDao {

	public CrawerBrand findCrawerBrandById(Integer id);
	
	public Integer insert(CrawerBrand param);
	
	public Integer getCrawerBrandCount(CrawerBrand param);
	
	public List<CrawerBrand> findCrawerBrandsByPage(@Param("param")CrawerBrand param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteCrawerBrandById(Integer id);

	public List<CrawerBrand> getBrandList();
}