package com.yd.service.crawer.dao;

import java.util.List;
import java.lang.Integer;
import org.apache.ibatis.annotations.Param;
import com.yd.service.crawer.bean.CrawerSiteSku;
import com.yd.api.crawer.req.CrawerSiteSkuReq;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface CrawerSiteSkuDao {

	public CrawerSiteSku findCrawerSiteSkuById(Integer id);
	
	public Integer insert(CrawerSiteSku param);
	
	public Integer getCrawerSiteSkuCount(CrawerSiteSkuReq req);
	
	public List<CrawerSiteSku> findCrawerSiteSkusByPage(@Param("req")CrawerSiteSkuReq req,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteCrawerSiteSkuById(Integer id);

	public List<CrawerSiteSku> getUndoSkuList();

	public int updateSkuByLink(@Param("param")CrawerSiteSku item);

	public CrawerSiteSku findCrawerSiteSkuByLink(@Param("link")String link);

	public List<CrawerSiteSku> getCoverNullList();
}