package com.yd.service.crawer.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yd.api.crawer.req.CrawerTmallItemReq;
import com.yd.service.crawer.bean.CrawerTmallItem;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface CrawerTmallItemDao {

	public CrawerTmallItem findCrawerTmallItemById(Integer id);
	
	public Integer insert(CrawerTmallItem param);
	
	public Integer getCrawerTmallItemCount(CrawerTmallItemReq req);
	
	public List<CrawerTmallItem> findCrawerTmallItemsByPage(@Param("req")CrawerTmallItemReq req,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteCrawerTmallItemById(Integer id);

	public List<CrawerTmallItem> getUndoTmallItem();

	public void updateTmallItemStatus(@Param("id")Integer id);

	public void updateTmallItemTitle(@Param("id")Integer id, @Param("itemTitle")String itemTitle);
}