package com.yd.service.crawer.dao;

import java.util.List;
import java.lang.Integer;
import org.apache.ibatis.annotations.Param;
import com.yd.service.crawer.bean.YdBijia;
import com.yd.api.crawer.req.YdBijiaReq;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface YdBijiaDao {

	public YdBijia findYdBijiaById(Integer id);
	
	public Integer insert(YdBijia param);
	
	public Integer getYdBijiaCount(YdBijiaReq req);
	
	public List<YdBijia> findYdBijiasByPage(@Param("req")YdBijiaReq req,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteYdBijiaById(Integer id);

	public YdBijia findYdBijiaBySkuId(@Param("skuId")int skuId);

	public int updateBySkuId(@Param("param")YdBijia bijia);
}