package com.yd.service.dao.common;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yd.service.bean.common.WbAlipayAccount;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface WbAlipayAccountDao {

	public WbAlipayAccount findWbAlipayAccountById(Integer id);
	
	public Integer insert(WbAlipayAccount param);
	
	public Integer getWbAlipayAccountCount(WbAlipayAccount param);
	
	public List<WbAlipayAccount> findWbAlipayAccountsByPage(@Param("param")WbAlipayAccount param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteWbAlipayAccountById(Integer id);

	public WbAlipayAccount findDefaultAlipayAccount();
}