package com.yd.service.dao.common;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yd.service.bean.common.WbPaySecret;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface WbPaySecretDao {

	public WbPaySecret findWbPaySecretById(Integer id);
	
	public Integer insert(WbPaySecret param);
	
	public Integer getWbPaySecretCount(WbPaySecret param);
	
	public List<WbPaySecret> findWbPaySecretsByPage(@Param("param")WbPaySecret param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteWbPaySecretById(Integer id);
}