package com.yd.service.dao.common;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yd.service.bean.common.WbPayOrder;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface WbPayOrderDao {

	public WbPayOrder findWbPayOrderById(Integer id);
	
	public Integer insert(WbPayOrder param);
	
	public Integer getWbPayOrderCount(WbPayOrder param);
	
	public List<WbPayOrder> findWbPayOrdersByPage(@Param("param")WbPayOrder param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteWbPayOrderById(Integer id);
	
	public int payNotifyWithPayAccountId(@Param("id")int id, @Param("amount")double amount,@Param("billNo") String billNo,@Param("payTime") Date payTime,
			@Param("payMethod")String payMethod, @Param("accountId")Integer accountId);

	public WbPayOrder findQyPayOrderByOutOrderId(@Param("outOrderId")String outOrderId);
}