package com.yd.service.dao.common;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yd.service.bean.common.WbWeixinAccount;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface WbWeixinAccountDao {

	public WbWeixinAccount findWbWeixinAccountById(Integer id);
	
	public Integer insert(WbWeixinAccount param);
	
	public Integer getWbWeixinAccountCount(WbWeixinAccount param);
	
	public List<WbWeixinAccount> findWbWeixinAccountsByPage(@Param("param")WbWeixinAccount param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteWbWeixinAccountById(Integer id);

	public WbWeixinAccount getByWeixinAccountByType(@Param("type")String type);

	public void updateAccessTokenWithTicket(@Param("param")WbWeixinAccount account);

	public WbWeixinAccount findDefaultWexinAccount();
}