package com.yd.service.dao.common;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yd.service.bean.common.WxKeywordsArticle;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface WxKeywordsArticleDao {

	public WxKeywordsArticle findWxKeywordsArticleById(Integer id);
	
	public Integer insert(WxKeywordsArticle param);
	
	public Integer getWxKeywordsArticleCount(WxKeywordsArticle param);
	
	public List<WxKeywordsArticle> findWxKeywordsArticlesByPage(@Param("param")WxKeywordsArticle param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteWxKeywordsArticleById(Integer id);
}