package com.yd.service.dao.common;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yd.service.bean.common.WxVisitRecord;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface WxVisitRecordDao {

	public WxVisitRecord findWxVisitRecordById(Integer id);
	
	public Integer insert(WxVisitRecord param);
	
	public Integer getWxVisitRecordCount(WxVisitRecord param);
	
	public List<WxVisitRecord> findWxVisitRecordsByPage(@Param("param")WxVisitRecord param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteWxVisitRecordById(Integer id);
}